name: Deploy Assignments

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Get Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Clone test Repository
      run: |
        git clone --depth 1 git@github.com:testkapua/test.git

    - name: Run deploy_assignments.py
      run: |
        python3 deploy_assignments.py
