name: Sync to Destination Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: testkapua/main
        token: ${{ secrets.SYNC_TOKEN }}
        ref: main

    - name: Sync to destination repository
      env:
        DEST_REPO_PAT: ${{ secrets.SYNC_TOKEN }}
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add destination https://$SYNC_TOKEN@github.com/testkapua/test.git
        git push --force destination main

